= Step 9: Verify Distribution Staging

== Description

Following are the typical things we need to verify before voting on a release candidate. And the release manager should verify them too before calling out a vote.

Make sure release artifacts are hosted at https://dist.apache.org/repos/dist/dev/fineract

* Release candidate files should match filenames mentioned earlier, and will be moved without renaming if/when the release vote passes.
* Verify signatures and hashes. You may have to import the public key of the release manager to verify the signatures. (`gpg --import KEYS` or `gpg --recv-key <key id>`)
* Git tag matches the released bits (`diff -rf`)
* Can compile docs and code successfully from source
* Verify DISCLAIMER, NOTICE and LICENSE (year etc)
* All files have correct headers (Rat check should be clean - `./gradlew rat`)
* No jar files in the source artifacts
* Integration tests should work

Code examples:

[source,bash,subs="attributes+"]
----
# source tarball signature and checksum verification steps
# we'll check the source tarball first
version=1.12.0
src=apache-fineract-$version-src.tar.gz

# upon success: prints "Good signature" and returns successful exit code
# upon failure: prints "BAD signature" and returns error exit code
gpg --verify $src.asc

# upon success: prints nothing and returns successful exit code
# upon failure: prints checksum differences and returns error exit code
gpg --print-md SHA512 $src | diff - $src.sha512

# binary tarball signature and checksum verification steps and outputs are similar
bin=apache-fineract-$version-binary.tar.gz
gpg --verify $bin.asc
gpg --print-md SHA512 $bin | diff - $bin.sha512
----

== Gradle Task

.Command
[source,bash,subs="attributes+,+macros"]
----
% ./gradlew fineractReleaseStep9 -Pfineract.release.version={revnumber}
----

CAUTION: This task is not yet automated!
